Add support for embedded debug type
Using Enum.TryParse since "pdb-only" is not a supported value anyway. This is the error we get if we try to use <DebugType>pdb-only</DebugType>
> Error CS1902 : Invalid option 'pdb-only' for /debug; must be 'portable', 'embedded', 'full' or 'pdbonly'